name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ تعطيل buildx نهائيًا
      - name: Disable Docker Buildx
        run: |
          mkdir -p ~/.docker/cli-plugins
          rm -f ~/.docker/cli-plugins/docker-buildx

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ بناء الصورة باستخدام docker التقليدي
      - name: Build Docker image (classic docker)
        run: |
          /usr/bin/docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest .

      - name: Push Docker image
        run: |
          /usr/bin/docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest

