name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) سحب كود المشروع
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) عرض شكل الريبو (تشخيص)
      - name: Show repo structure
        run: ls -R

      # 3) تسجيل الدخول إلى DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Build Docker image
      - name: Build Docker image
        working-directory: projects/devops-app-flask
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest .

      # 5) Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest




